"""Render the priority table: one row per country, one column per score component.

No black box: the composite priority score is a weighted sum of the
component columns shown alongside it, and the weights are exposed as sliders
so the ranking's sensitivity is visible, not hidden.
"""

from __future__ import annotations

import pandas as pd
import streamlit as st

from recipe.attribution import Citation, require_citations
from recipe.i18n import Translator


def render_priority_table(
    scored_df: pd.DataFrame,
    citations: list[Citation],
    t: Translator,
    headline_total_unserved: float | None = None,
) -> None:
    require_citations(citations)

    # The old English copy hardcoded "electrification" here, but this tab
    # renders for any indicator that has a denominator -- the wording is
    # indicator-neutral now.
    st.subheader(t.t("priority.title"))

    if headline_total_unserved is not None:
        st.metric(
            t.t("priority.headline"),
            t.millions(headline_total_unserved),
        )

    st.caption(t.t("priority.explainer"))

    display_cols = ["place_name", "priority_score"] + [
        c for c in scored_df.columns if c.startswith("rank_")
    ]
    display_cols = [c for c in display_cols if c in scored_df.columns]

    st.dataframe(
        scored_df[display_cols].reset_index(drop=True),
        use_container_width=True,
        # Keys are the dataframe's column ids, generated by
        # gap_scoring.priority_score from the `components` dict in app.py --
        # they are program identifiers, never display text. Only the values
        # are translated; renaming a key here silently drops its header.
        column_config={
            "place_name": t.t("priority.col_country"),
            "priority_score": st.column_config.ProgressColumn(
                t.t("priority.col_priority"), min_value=0, max_value=1
            ),
            "rank_unserved_pop": t.t("priority.col_people"),
            "rank_stagnation": t.t("priority.col_stagnation"),
        },
    )

    for c in citations:
        st.caption(t.t("source.prefix", citation=c.render(t)))
