/* Fill in any blank/missing country display name in data/world-geo.js from the
   Data Commons /node endpoint. The original prototype shipped 19 empty names for
   off-map territories (Singapore, Seychelles, Tuvalu...), which rendered as blanks
   in the table and tooltip.
   Usage: node scripts/fill-names.mjs [ISO3 ...]   (no args = every blank in world-geo.js) */
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const cfg = JSON.parse(readFileSync(resolve(root, "scripts/indicators.config.json"), "utf8"));
const path = resolve(root, "data/world-geo.js");
const src = readFileSync(path, "utf8");
const geo = JSON.parse(src.slice(src.indexOf("{"), src.lastIndexOf("}") + 1));

/* Emit pure ASCII: these files are loaded as classic <script> and servers rarely
   set a charset on .js, so a raw UTF-8 name like "S\u00e3o Tom\u00e9" would mojibake.
   The original prototype's data file was escaped the same way. */
const ascii = (o) => JSON.stringify(o).replace(/[\u007f-\uffff]/g,
  (c) => "\\u" + c.charCodeAt(0).toString(16).padStart(4, "0"));


// also consider ISO3s that appear in indicator series but not in the names map at all
const known = new Set(Object.keys(geo.names));
const fromArgs = process.argv.slice(2);
const blanks = fromArgs.length
  ? fromArgs
  : Object.keys(geo.names).filter((k) => !geo.names[k]).concat(
      cfg.indicators.flatMap((i) => {
        try {
          const s = readFileSync(resolve(root, `data/indicators/${i.slug}.js`), "utf8");
          const d = JSON.parse(s.slice(s.indexOf('"series"') > 0 ? s.lastIndexOf("={") + 1 : 0, s.lastIndexOf("}") + 1));
          return Object.keys(d.series).filter((k) => !known.has(k));
        } catch { return []; }
      })
    );

const todo = [...new Set(blanks)];
if (!todo.length) { console.error("no blank names"); process.exit(0); }

let filled = 0;
for (const iso of todo) {
  const u = new URL(cfg.rest + "/node");
  u.searchParams.set("nodes", `country/${iso}`);   // one node per request: the API ignores lists
  u.searchParams.set("property", "->name");
  const r = await fetch(u);
  const j = await r.json();
  const name = j?.data?.[`country/${iso}`]?.arcs?.name?.nodes?.[0]?.value;
  if (name) { geo.names[iso] = name; filled++; console.error(`  ${iso} -> ${name}`); }
  else console.error(`  ${iso} -> UNRESOLVED`);
}

writeFileSync(path, "/* generated by scripts/split-geo.mjs -- do not edit */\nwindow.UNGEO=" + ascii(geo) + ";\n");
console.error(`filled ${filled}/${todo.length}`);
