/* One-shot: lift the GeoJSON + country names out of the original fused data file
   into data/world-geo.js, so geometry ships once instead of per indicator.
   One-shot, already applied: it reads the original fused data/renewable-share.js,
   which was removed once data/world-geo.js was verified. Kept as the record of how
   the basemap was derived; restore that file from git history to re-run it.
   Usage: node scripts/split-geo.mjs */
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const src = readFileSync(resolve(root, "data/renewable-share.js"), "utf8");

/* Emit pure ASCII: these files are loaded as classic <script> and servers rarely
   set a charset on .js, so a raw UTF-8 name like "S\u00e3o Tom\u00e9" would mojibake.
   The original prototype's data file was escaped the same way. */
const ascii = (o) => JSON.stringify(o).replace(/[\u007f-\uffff]/g,
  (c) => "\\u" + c.charCodeAt(0).toString(16).padStart(4, "0"));


// file is `window.UNDATA={...};` on one line
const json = src.slice(src.indexOf("{"), src.lastIndexOf("}") + 1);
const D = JSON.parse(json);

if (!D.geo || !Array.isArray(D.geo.features)) throw new Error("no geo.features in source");

// canonical names: prefer the curated D.names, fall back to the feature's own property
const names = { ...D.names };
for (const f of D.geo.features) {
  if (f.id && !names[f.id] && f.properties && f.properties.name) names[f.id] = f.properties.name;
}

const out = {
  type: D.geo.type,
  features: D.geo.features,
  names,
};

writeFileSync(
  resolve(root, "data/world-geo.js"),
  "/* generated by scripts/split-geo.mjs -- do not edit */\nwindow.UNGEO=" + ascii(out) + ";\n"
);

console.error(`world-geo.js: ${out.features.length} features, ${Object.keys(names).length} names`);
